CREATE SCHEMA IF NOT EXISTS car_rental_company DEFAULT CHARACTER SET utf8 ;
USE car_rental_company ;

CREATE TABLE IF NOT EXISTS car_rental_company.OFFICE (
    ID INT NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(45) NOT NULL,
    PHONE_NUMBER VARCHAR(12) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS car_rental_company.COMPANY_POSITION (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX name_UNIQUE (NAME ASC)
);


CREATE TABLE IF NOT EXISTS car_rental_company.EMPLOYEE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    OFFICE_ID INT NOT NULL,
    COMPANY_POSITION_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_office_employee FOREIGN KEY (OFFICE_ID)
        REFERENCES car_rental_company.OFFICE (ID),
    CONSTRAINT fk_employee_position FOREIGN KEY (COMPANY_POSITION_ID)
        REFERENCES car_rental_company.COMPANY_POSITION (ID)
);


CREATE TABLE IF NOT EXISTS car_rental_company.CUSTOMER (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    SURNAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(60) NULL,
    PHONE_NUMBER VARCHAR(12) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    CREDIT_CARD_NUMBER VARCHAR(16) NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS car_rental_company.COLOR (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX name_UNIQUE (NAME ASC)
);

CREATE TABLE IF NOT EXISTS car_rental_company.CAR_TYPE (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX name_UNIQUE (NAME ASC)
);


CREATE TABLE IF NOT EXISTS car_rental_company.CAR (
    ID INT NOT NULL AUTO_INCREMENT,
    MILEAGE VARCHAR(30) NULL,
    BRAND VARCHAR(30) NOT NULL,
    MODEL VARCHAR(30) NOT NULL,
    CAR_TYPE_ID INT NOT NULL,
    ENGINE_CAPACITY INT NOT NULL,
    HORSEPOWER INT NOT NULL,
    YEAR_OF_MANUFACTURE INT NOT NULL,
    COLOR_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_car_color FOREIGN KEY (COLOR_ID)
        REFERENCES car_rental_company.COLOR (ID)
        ON DELETE NO ACTION,
	CONSTRAINT fk_car_type FOREIGN KEY (CAR_TYPE_ID)
	REFERENCES car_rental_company.CAR_TYPE (ID)
	ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS car_rental_company.LOAN (
    ID INT NOT NULL AUTO_INCREMENT,
    OFFICE_FROM_ID INT NOT NULL,
    OFFICE_TO_ID INT NOT NULL,
    CAR_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    DATE_FROM DATE NOT NULL,
    DATE_TO DATE NOT NULL,
    PRICE INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_office_from FOREIGN KEY (OFFICE_FROM_ID)
        REFERENCES car_rental_company.OFFICE (ID),
    CONSTRAINT fk_office_to FOREIGN KEY (OFFICE_TO_ID)
        REFERENCES car_rental_company.OFFICE (ID),
    CONSTRAINT fk_loaned_car FOREIGN KEY (CAR_ID)
        REFERENCES car_rental_company.CAR (ID),
    CONSTRAINT fk_loaning_customer FOREIGN KEY (CUSTOMER_ID)
        REFERENCES car_rental_company.CUSTOMER (ID)
);


CREATE TABLE IF NOT EXISTS car_rental_company.KEEPER(
 ID INT NOT NULL AUTO_INCREMENT,
 EMPLOYEE_ID INT NOT NULL,
 CAR_ID INT NOT NULL,
 PRIMARY KEY(ID),
 CONSTRAINT fk_keeping_employee
    FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES car_rental_company.EMPLOYEE(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 CONSTRAINT fk_keeped_car
    FOREIGN KEY (CAR_ID)
    REFERENCES car_rental_company.CAR(ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );




